---
title: Dork Jedi
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 'The home for things I believe are worthy of a Dork Jedi.

'
baseurl: ''
url: http://dorkjedi.github.io
twitter_username: hoagie
github_username: dorkjedi
markdown: kramdown
highlighter: rouge
